<?php
// /setup.php (نسخه اصلاح شده)
session_start();
error_reporting(E_ALL);
ini_set('display_errors', 1);

$step = $_GET['step'] ?? 1;
$config_file_path = __DIR__ . '/api/config.php';
$error_message = '';

// اگر فایل کانفیگ از قبل موجود است، به مرحله آخر برو
if (file_exists($config_file_path) && $step != 3) {
    $step = 3;
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && $step == 2) {
    $db_host = $_POST['db_host'] ?? 'localhost';
    $db_name = $_POST['db_name'] ?? '';
    $db_user = $_POST['db_user'] ?? '';
    $db_pass = $_POST['db_pass'] ?? '';

    if (empty($db_name) || empty($db_user)) {
        $error_message = 'نام دیتابیس و نام کاربری الزامی است.';
    } else {
        // ۱. ایجاد فایل کانفیگ
        $config_content = "<?php\n// /api/config.php - Generated by setup script\n\n";
        $config_content .= "define('DB_SERVER', '{$db_host}');\n";
        $config_content .= "define('DB_NAME', '{$db_name}');\n";
        $config_content .= "define('DB_USERNAME', '{$db_user}');\n";
        $config_content .= "define('DB_PASSWORD', '{$db_pass}');\n";

        if (file_put_contents($config_file_path, $config_content) === false) {
            $error_message = 'خطا در ایجاد فایل `config.php`. لطفاً از قابل نوشتن بودن پوشه `api/` اطمینان حاصل کنید.';
        } else {
            try {
                // ۲. اتصال به سرور دیتابیس و ایجاد دیتابیس
                $pdo = new PDO("mysql:host={$db_host}", $db_user, $db_pass, [
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
                ]);
                $pdo->exec("CREATE DATABASE IF NOT EXISTS `{$db_name}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
                $pdo->exec("USE `{$db_name}`");

                // ۳. ایجاد جداول
                $sql_statements = get_sql_schema();
                foreach ($sql_statements as $statement) {
                    $pdo->exec($statement);
                }

                // ۴. ایجاد کاربر پیش‌فرض
                $admin_user = 'admin';
                $admin_pass = 'admin123';
                $password_hash = password_hash($admin_pass, PASSWORD_DEFAULT);

                $stmt = $pdo->prepare("INSERT INTO `users` (username, password_hash) VALUES (?, ?)");
                $stmt->execute([$admin_user, $password_hash]);

                // انتقال به مرحله پایانی
                header('Location: setup.php?step=3');
                exit;

            } catch (PDOException $e) {
                $error_message = "خطا در اتصال یا اجرای دستورات دیتابیس: " . $e->getMessage();
                // در صورت خطا، فایل کانفیگ را حذف کن تا کاربر دوباره تلاش کند
                if(file_exists($config_file_path)) {
                    unlink($config_file_path);
                }
            }
        }
    }
}

function get_sql_schema() {
    return [
        "CREATE TABLE IF NOT EXISTS `accounts` (
          `id` int(11) NOT NULL AUTO_INCREMENT,
          `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
          `bank_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
          `account_number` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
          `card_number` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
          `current_balance` decimal(15,2) NOT NULL DEFAULT 0.00,
          `is_cash` tinyint(1) NOT NULL DEFAULT 0,
          PRIMARY KEY (`id`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",

        "CREATE TABLE IF NOT EXISTS `activity_log` (
          `id` int(11) NOT NULL AUTO_INCREMENT,
          `user_id` int(11) DEFAULT NULL,
          `timestamp` timestamp NOT NULL DEFAULT current_timestamp(),
          `username` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
          `action_type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
          `description` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
          PRIMARY KEY (`id`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",

        "CREATE TABLE IF NOT EXISTS `customers` (
          `id` int(11) NOT NULL AUTO_INCREMENT,
          `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
          `address` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
          `phone` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
          `nationalId` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
          `initial_balance` decimal(15,2) DEFAULT 0.00,
          PRIMARY KEY (`id`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",

        "CREATE TABLE IF NOT EXISTS `suppliers` (
          `id` int(11) NOT NULL AUTO_INCREMENT,
          `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
          `address` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
          `phone` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
          `economicCode` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
          `initial_balance` decimal(15,2) DEFAULT 0.00,
          PRIMARY KEY (`id`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",

        "CREATE TABLE IF NOT EXISTS `products` (
          `id` int(11) NOT NULL AUTO_INCREMENT,
          `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
          `description` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
          PRIMARY KEY (`id`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",

        "CREATE TABLE IF NOT EXISTS `product_stock` (
          `id` int(11) NOT NULL AUTO_INCREMENT,
          `product_id` int(11) NOT NULL,
          `dimensions` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
          `quantity` int(11) NOT NULL DEFAULT 0,
          PRIMARY KEY (`id`),
          KEY `product_id` (`product_id`),
          CONSTRAINT `product_stock_ibfk_1` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",

        "CREATE TABLE IF NOT EXISTS `sales_invoices` (
          `id` int(11) NOT NULL AUTO_INCREMENT,
          `customerId` int(11) NOT NULL,
          `date` date NOT NULL,
          `totalAmount` decimal(15,2) NOT NULL,
          `discount` decimal(15,2) DEFAULT 0.00,
          `paidAmount` decimal(15,2) DEFAULT 0.00,
          `description` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
          `is_consignment` tinyint(1) DEFAULT 0,
          PRIMARY KEY (`id`),
          KEY `customerId` (`customerId`),
          CONSTRAINT `sales_invoices_ibfk_1` FOREIGN KEY (`customerId`) REFERENCES `customers` (`id`) ON DELETE RESTRICT
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",

        "CREATE TABLE IF NOT EXISTS `sales_invoice_items` (
          `id` int(11) NOT NULL AUTO_INCREMENT,
          `invoiceId` int(11) NOT NULL,
          `productId` int(11) NOT NULL,
          `quantity` int(11) NOT NULL,
          `unitPrice` decimal(15,2) NOT NULL,
          `dimensions` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
          PRIMARY KEY (`id`),
          KEY `invoiceId` (`invoiceId`),
          CONSTRAINT `sales_invoice_items_ibfk_1` FOREIGN KEY (`invoiceId`) REFERENCES `sales_invoices` (`id`) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",

        "CREATE TABLE IF NOT EXISTS `purchase_invoices` (
          `id` int(11) NOT NULL AUTO_INCREMENT,
          `supplierId` int(11) NOT NULL,
          `date` date NOT NULL,
          `totalAmount` decimal(15,2) NOT NULL,
          `discount` decimal(15,2) DEFAULT 0.00,
          `paidAmount` decimal(15,2) DEFAULT 0.00,
          `description` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
          `is_consignment` tinyint(1) DEFAULT 0,
          PRIMARY KEY (`id`),
          KEY `supplierId` (`supplierId`),
          CONSTRAINT `purchase_invoices_ibfk_1` FOREIGN KEY (`supplierId`) REFERENCES `suppliers` (`id`) ON DELETE RESTRICT
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",

        "CREATE TABLE IF NOT EXISTS `purchase_invoice_items` (
          `id` int(11) NOT NULL AUTO_INCREMENT,
          `invoiceId` int(11) NOT NULL,
          `productId` int(11) NOT NULL,
          `quantity` int(11) NOT NULL,
          `unitPrice` decimal(15,2) NOT NULL,
          `dimensions` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
          PRIMARY KEY (`id`),
          KEY `invoiceId` (`invoiceId`),
          CONSTRAINT `purchase_invoice_items_ibfk_1` FOREIGN KEY (`invoiceId`) REFERENCES `purchase_invoices` (`id`) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
        
        "CREATE TABLE IF NOT EXISTS `checks` (
          `id` int(11) NOT NULL AUTO_INCREMENT,
          `type` enum('received','payable') COLLATE utf8mb4_unicode_ci NOT NULL,
          `status` enum('in_hand','endorsed','cashed','payable','bounced') COLLATE utf8mb4_unicode_ci NOT NULL,
          `invoiceId` int(11) DEFAULT NULL,
          `invoiceType` enum('sales','purchase') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
          `checkNumber` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
          `dueDate` date NOT NULL,
          `bankName` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
          `amount` decimal(15,2) NOT NULL,
          `endorsedToInvoiceId` int(11) DEFAULT NULL,
          `cashed_in_account_id` int(11) DEFAULT NULL,
          PRIMARY KEY (`id`),
          KEY `cashed_in_account_id` (`cashed_in_account_id`),
          CONSTRAINT `checks_ibfk_1` FOREIGN KEY (`cashed_in_account_id`) REFERENCES `accounts` (`id`) ON DELETE SET NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
        
        "CREATE TABLE IF NOT EXISTS `payments` (
          `id` int(11) NOT NULL AUTO_INCREMENT,
          `invoiceId` int(11) NOT NULL,
          `invoiceType` enum('sales','purchase') COLLATE utf8mb4_unicode_ci NOT NULL,
          `type` enum('cash','check','endorse_check') COLLATE utf8mb4_unicode_ci NOT NULL,
          `amount` decimal(15,2) NOT NULL,
          `date` date NOT NULL,
          `description` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
          `checkId` int(11) DEFAULT NULL,
          `account_id` int(11) DEFAULT NULL,
          PRIMARY KEY (`id`),
          KEY `checkId` (`checkId`),
          KEY `account_id` (`account_id`),
          CONSTRAINT `payments_ibfk_1` FOREIGN KEY (`checkId`) REFERENCES `checks` (`id`) ON DELETE SET NULL,
          CONSTRAINT `payments_ibfk_2` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE SET NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",

        "CREATE TABLE IF NOT EXISTS `expenses` (
          `id` int(11) NOT NULL AUTO_INCREMENT,
          `category` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
          `date` date NOT NULL,
          `amount` decimal(15,2) NOT NULL,
          `description` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
          `account_id` int(11) NOT NULL,
          PRIMARY KEY (`id`),
          KEY `account_id` (`account_id`),
          CONSTRAINT `expenses_ibfk_1` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE RESTRICT
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",

        "CREATE TABLE IF NOT EXISTS `partners` (
          `id` int(11) NOT NULL AUTO_INCREMENT,
          `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
          `share` decimal(5,4) NOT NULL,
          PRIMARY KEY (`id`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
        
        "CREATE TABLE IF NOT EXISTS `partner_transactions` (
          `id` int(11) NOT NULL AUTO_INCREMENT,
          `partnerId` int(11) NOT NULL,
          `type` enum('DEPOSIT','WITHDRAWAL') COLLATE utf8mb4_unicode_ci NOT NULL,
          `date` date NOT NULL,
          `amount` decimal(15,2) NOT NULL,
          `description` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
          `account_id` int(11) NOT NULL,
          PRIMARY KEY (`id`),
          KEY `partnerId` (`partnerId`),
          KEY `account_id` (`account_id`),
          CONSTRAINT `partner_transactions_ibfk_1` FOREIGN KEY (`partnerId`) REFERENCES `partners` (`id`) ON DELETE RESTRICT,
          CONSTRAINT `partner_transactions_ibfk_2` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE RESTRICT
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",

        "CREATE TABLE IF NOT EXISTS `transactions` (
          `id` int(11) NOT NULL AUTO_INCREMENT,
          `relatedObjectType` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
          `relatedObjectId` int(11) NOT NULL,
          `amount` decimal(15,2) NOT NULL,
          `date` date NOT NULL,
          `type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
          `description` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
          PRIMARY KEY (`id`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",

        "CREATE TABLE IF NOT EXISTS `users` (
          `id` int(11) NOT NULL AUTO_INCREMENT,
          `username` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
          `password_hash` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
          PRIMARY KEY (`id`),
          UNIQUE KEY `username` (`username`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;"
    ];
}
?>
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>نصب و راه‌اندازی سیستم حسابداری</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; direction: rtl; background-color: #f8f9fa; margin: 0; padding: 20px; display: flex; justify-content: center; align-items: center; min-height: 100vh; }
        .container { background: #fff; padding: 2rem; border-radius: 8px; box-shadow: 0 4px 12px rgba(0,0,0,0.1); max-width: 600px; width: 100%; text-align: right; }
        h1 { color: #333; }
        .form-group { margin-bottom: 1.5rem; }
        label { display: block; margin-bottom: .5rem; font-weight: bold; color: #555; }
        input[type="text"], input[type="password"] { width: calc(100% - 20px); padding: 10px; border: 1px solid #ccc; border-radius: 4px; font-size: 1rem; text-align: left; direction: ltr; }
        .btn { display: inline-block; padding: 10px 20px; border-radius: 4px; border: none; font-size: 1rem; font-weight: bold; cursor: pointer; text-decoration: none; text-align: center; }
        .btn-primary { background-color: #0d6efd; color: #fff; }
        .btn-success { background-color: #198754; color: #fff; }
        .alert { padding: 1rem; border-radius: 4px; margin-bottom: 1rem; }
        .alert-danger { background-color: #f8d7da; color: #721c24; border: 1px solid #f5c6cb; }
        .alert-success { background-color: #d4edda; color: #155724; border: 1px solid #c3e6cb; }
        .alert-warning { background-color: #fff3cd; color: #856404; border: 1px solid #ffeeba; }
        code { background-color: #e9ecef; padding: .2em .4em; margin: 0; font-size: 85%; border-radius: 3px; }
    </style>
</head>
<body>
    <div class="container">
        <?php if ($step == 1): ?>
            <h1>مرحله ۱: خوش آمدید!</h1>
            <p>این اسکریپت شما را در راه‌اندازی سیستم حسابداری یاری می‌کند. لطفاً اطلاعات اتصال به دیتابیس خود را در فرم زیر وارد کنید.</p>
            <p>اسکریپت به صورت خودکار فایل `config.php` را ایجاد کرده و جداول مورد نیاز را در دیتابیس شما نصب خواهد کرد.</p>
            
            <?php if ($error_message): ?>
                <div class="alert alert-danger"><?php echo htmlspecialchars($error_message); ?></div>
            <?php endif; ?>

            <form action="setup.php?step=2" method="POST">
                <div class="form-group">
                    <label for="db_host">آدرس هاست دیتابیس</label>
                    <input type="text" id="db_host" name="db_host" value="localhost" required>
                </div>
                <div class="form-group">
                    <label for="db_name">نام دیتابیس</label>
                    <input type="text" id="db_name" name="db_name" required placeholder="hesabdari_db">
                </div>
                <div class="form-group">
                    <label for="db_user">نام کاربری دیتابیس</label>
                    <input type="text" id="db_user" name="db_user" required>
                </div>
                <div class="form-group">
                    <label for="db_pass">رمز عبور دیتابیس</label>
                    <input type="password" id="db_pass" name="db_pass">
                </div>
                <button type="submit" class="btn btn-primary">شروع نصب</button>
            </form>

        <?php elseif ($step == 2): ?>
            <h1>مرحله ۲: در حال نصب...</h1>
             <?php if ($error_message): ?>
                <div class="alert alert-danger">
                    <strong>خطا در نصب:</strong><br>
                    <?php echo htmlspecialchars($error_message); ?><br><br>
                    <a href="setup.php" class="btn btn-primary">دوباره تلاش کنید</a>
                </div>
            <?php else: ?>
                <p>لطفاً منتظر بمانید...</p>
            <?php endif; ?>

        <?php elseif ($step == 3): ?>
            <h1>مرحله پایانی: نصب با موفقیت انجام شد!</h1>
            <div class="alert alert-success">
                سیستم حسابداری شما با موفقیت نصب و راه‌اندازی شد.
            </div>
            <p>می‌توانید با اطلاعات زیر وارد سیستم شوید:</p>
            <ul>
                <li><strong>نام کاربری:</strong> <code>admin</code></li>
                <li><strong>رمز عبور:</strong> <code>admin123</code></li>
            </ul>
            <p>پس از ورود، حتماً از طریق بخش "تغییر رمز" رمز عبور خود را تغییر دهید.</p>
            
            <div class="alert alert-warning">
                <strong>هشدار امنیتی بسیار مهم:</strong><br>
                برای جلوگیری از دسترسی غیرمجاز و نصب مجدد، لطفاً فوراً فایل `setup.php` را از روی سرور خود حذف کنید.
            </div>
            
            <a href="index.html" class="btn btn-success">ورود به برنامه</a>
        <?php endif; ?>
    </div>
</body>
</html>